TRUNCATE TABLE coding_questions RESTART IDENTITY CASCADE;
INSERT INTO coding_questions
(topic_id, title, difficulty, companies, platform, problem_url, display_order)
VALUES
(101,'Largest Element in Array','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'GFG','https://www.geeksforgeeks.org/problems/largest-element-in-array4009/1',1),
(101,'Second Largest','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'GFG','https://www.geeksforgeeks.org/problems/second-largest3735/1',2),
(101,'Check if Array Is Sorted and Rotated','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/',3),
(102,'Remove Duplicates from Sorted Array','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/remove-duplicates-from-sorted-array/',1),
(102,'Move Zeroes','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/move-zeroes/',2),
(102,'Missing Number','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/missing-number/',3),
(103,'Two Sum','EASY',ARRAY['Amazon','Google','Microsoft','Meta','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/two-sum/',1),
(103,'Sort Colors','MEDIUM',ARRAY['Amazon','Microsoft','Google','Adobe']::TEXT[],'LEETCODE','https://leetcode.com/problems/sort-colors/',2),
(103,'Next Permutation','MEDIUM',ARRAY['Amazon','Google','Microsoft','Adobe']::TEXT[],'LEETCODE','https://leetcode.com/problems/next-permutation/',3),
(104,'First Missing Positive','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/first-missing-positive/',1),
(104,'Trapping Rain Water','HARD',ARRAY['Amazon','Google','Microsoft','Meta','Goldman Sachs']::TEXT[],'LEETCODE','https://leetcode.com/problems/trapping-rain-water/',2),
(104,'Median of Two Sorted Arrays','HARD',ARRAY['Google','Amazon','Microsoft','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/median-of-two-sorted-arrays/',3),
(105,'Maximum Subarray','MEDIUM',ARRAY['Amazon','Microsoft','Google','Apple','LinkedIn']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-subarray/',1),
(105,'Subarray Sum Equals K','MEDIUM',ARRAY['Amazon','Google','Meta','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/subarray-sum-equals-k/',2),
(105,'Maximum Product Subarray','MEDIUM',ARRAY['Amazon','Microsoft','Google','LinkedIn']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-product-subarray/',3),
(106,'Maximum Sum Circular Subarray','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-sum-circular-subarray/',1),
(106,'Maximum Absolute Sum of Any Subarray','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-absolute-sum-of-any-subarray/',2),
(107,'Rotate Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/rotate-array/',1),
(107,'Rearrange Array Elements by Sign','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/rearrange-array-elements-by-sign/',2),
(107,'Wiggle Sort II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/wiggle-sort-ii/',3),
(108,'Majority Element','EASY',ARRAY['Amazon','Microsoft','Google','Adobe']::TEXT[],'LEETCODE','https://leetcode.com/problems/majority-element/',1),
(108,'Majority Element II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/majority-element-ii/',2),
(108,'Check If a Number Is Majority Element in a Sorted Array','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/check-if-a-number-is-majority-element-in-a-sorted-array/',3),
(109,'Find the Duplicate Number','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-the-duplicate-number/',1),
(109,'Set Mismatch','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/set-mismatch/',2),
(110,'Reverse Pairs','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-pairs/',1),
(110,'Count of Smaller Numbers After Self','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/count-of-smaller-numbers-after-self/',2),
(110,'Global and Local Inversions','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/global-and-local-inversions/',3),
(201,'Valid Anagram','EASY',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/valid-anagram/',1),
(201,'Reverse String','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-string/',2),
(201,'Longest Common Prefix','EASY',ARRAY['Amazon','Google','Microsoft','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-common-prefix/',3),
(202,'Valid Palindrome','EASY',ARRAY['Amazon','Meta','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/valid-palindrome/',1),
(202,'Longest Palindromic Substring','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-palindromic-substring/',2),
(202,'Palindromic Substrings','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/palindromic-substrings/',3),
(203,'Group Anagrams','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Uber']::TEXT[],'LEETCODE','https://leetcode.com/problems/group-anagrams/',1),
(203,'Find All Anagrams in a String','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-all-anagrams-in-a-string/',2),
(204,'Sort Characters By Frequency','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/sort-characters-by-frequency/',1),
(204,'First Unique Character in a String','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/first-unique-character-in-a-string/',2),
(204,'Minimum Window Substring','HARD',ARRAY['Amazon','Google','Meta','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-window-substring/',3),
(205,'Reverse Words in a String','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-words-in-a-string/',1),
(205,'String Compression','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/string-compression/',2),
(205,'Zigzag Conversion','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/zigzag-conversion/',3),
(206,'Find the Index of the First Occurrence in a String','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',1),
(206,'Repeated String Match','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/repeated-string-match/',2),
(206,'Repeated Substring Pattern','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/repeated-substring-pattern/',3),
(301,'Binary Search','EASY',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-search/',1),
(301,'Search Insert Position','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-insert-position/',2),
(301,'Sqrt(x)','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/sqrtx/',3),
(302,'Implement Lower Bound','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'GFG','https://www.geeksforgeeks.org/problems/implement-lower-bound/1',1),
(302,'Find First and Last Position of Element in Sorted Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',2),
(303,'Search in Rotated Sorted Array','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-in-rotated-sorted-array/',1),
(303,'Search in Rotated Sorted Array II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-in-rotated-sorted-array-ii/',2),
(303,'Find Minimum in Rotated Sorted Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',3),
(304,'Koko Eating Bananas','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/koko-eating-bananas/',1),
(304,'Minimum Number of Days to Make m Bouquets','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/',2),
(304,'Capacity To Ship Packages Within D Days','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',3),
(304,'Aggressive Cows','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'GFG','https://www.geeksforgeeks.org/problems/aggressive-cows/0',4),
(305,'Search a 2D Matrix','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-a-2d-matrix/',1),
(305,'Search a 2D Matrix II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-a-2d-matrix-ii/',2),
(305,'Find a Peak Element II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-a-peak-element-ii/',3),
(306,'Find Peak Element','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-peak-element/',1),
(306,'Peak Index in a Mountain Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/peak-index-in-a-mountain-array/',2),
(307,'Find Median from Data Stream','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-median-from-data-stream/',1),
(307,'Sliding Window Median','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/sliding-window-median/',2),
(308,'Split Array Largest Sum','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/split-array-largest-sum/',1),
(308,'Find K-th Smallest Pair Distance','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-k-th-smallest-pair-distance/',2),
(308,'Kth Smallest Element in a Sorted Matrix','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/',3),
(401,'Middle of the Linked List','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/middle-of-the-linked-list/',1),
(401,'Merge Two Sorted Lists','EASY',ARRAY['Amazon','Microsoft','Google','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/merge-two-sorted-lists/',2),
(401,'Remove Linked List Elements','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/remove-linked-list-elements/',3),
(402,'Delete Node in a Linked List','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/delete-node-in-a-linked-list/',1),
(402,'Remove Nth Node From End of List','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/remove-nth-node-from-end-of-list/',2),
(402,'Design Linked List','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/design-linked-list/',3),
(403,'Reverse Linked List','EASY',ARRAY['Amazon','Microsoft','Google','Meta','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-linked-list/',1),
(403,'Reverse Linked List II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-linked-list-ii/',2),
(403,'Reverse Nodes in k-Group','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/reverse-nodes-in-k-group/',3),
(404,'Linked List Cycle','EASY',ARRAY['Amazon','Microsoft','Google','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/linked-list-cycle/',1),
(404,'Happy Number','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/happy-number/',2),
(405,'Linked List Cycle II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/linked-list-cycle-ii/',1),
(406,'Merge k Sorted Lists','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/merge-k-sorted-lists/',1),
(406,'Sort List','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/sort-list/',2),
(501,'Valid Parentheses','EASY',ARRAY['Amazon','Google','Microsoft','Meta','Bloomberg']::TEXT[],'LEETCODE','https://leetcode.com/problems/valid-parentheses/',1),
(501,'Min Stack','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/min-stack/',2),
(501,'Evaluate Reverse Polish Notation','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/evaluate-reverse-polish-notation/',3),
(502,'Implement Queue using Stacks','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/implement-queue-using-stacks/',1),
(502,'Number of Recent Calls','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-recent-calls/',2),
(502,'Design Circular Queue','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/design-circular-queue/',3),
(505,'Daily Temperatures','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/daily-temperatures/',1),
(505,'Largest Rectangle in Histogram','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/largest-rectangle-in-histogram/',2),
(505,'Sum of Subarray Minimums','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/sum-of-subarray-minimums/',3),
(506,'Sliding Window Maximum','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/sliding-window-maximum/',1),
(506,'Shortest Subarray with Sum at Least K','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/',2),
(506,'Constrained Subsequence Sum','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/constrained-subsequence-sum/',3),
(507,'Next Greater Element I','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/next-greater-element-i/',1),
(507,'Next Greater Element II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/next-greater-element-ii/',2),
(507,'Next Greater Element III','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/next-greater-element-iii/',3),
(602,'Binary Tree Inorder Traversal','EASY',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-inorder-traversal/',1),
(602,'Binary Tree Preorder Traversal','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-preorder-traversal/',2),
(602,'Binary Tree Postorder Traversal','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-postorder-traversal/',3),
(603,'Binary Tree Level Order Traversal','MEDIUM',ARRAY['Amazon','Microsoft','Google','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-level-order-traversal/',1),
(603,'Binary Tree Zigzag Level Order Traversal','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',2),
(603,'Binary Tree Right Side View','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-right-side-view/',3),
(604,'Maximum Depth of Binary Tree','EASY',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-depth-of-binary-tree/',1),
(604,'Minimum Depth of Binary Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-depth-of-binary-tree/',2),
(604,'Maximum Depth of N-ary Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-depth-of-n-ary-tree/',3),
(605,'Diameter of Binary Tree','EASY',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/diameter-of-binary-tree/',1),
(605,'Binary Tree Maximum Path Sum','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/binary-tree-maximum-path-sum/',2),
(605,'Longest Univalue Path','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-univalue-path/',3),
(606,'Balanced Binary Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/balanced-binary-tree/',1),
(606,'Symmetric Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/symmetric-tree/',2),
(606,'Same Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/same-tree/',3),
(609,'Lowest Common Ancestor of a Binary Tree','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',1),
(609,'Lowest Common Ancestor of a Binary Search Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',2),
(609,'Lowest Common Ancestor of Deepest Leaves','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/lowest-common-ancestor-of-deepest-leaves/',3),
(611,'Construct Binary Tree from Preorder and Inorder Traversal','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',1),
(611,'Construct Binary Tree from Inorder and Postorder Traversal','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/',2),
(611,'Construct Binary Search Tree from Preorder Traversal','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/',3),
(612,'Serialize and Deserialize Binary Tree','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',1),
(612,'Serialize and Deserialize BST','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/serialize-and-deserialize-bst/',2),
(612,'Verify Preorder Serialization of a Binary Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/',3),
(701,'Kth Largest Element in an Array','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/kth-largest-element-in-an-array/',1),
(701,'Last Stone Weight','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/last-stone-weight/',2),
(701,'K Closest Points to Origin','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/k-closest-points-to-origin/',3),
(704,'Top K Frequent Elements','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/top-k-frequent-elements/',1),
(704,'Top K Frequent Words','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/top-k-frequent-words/',2),
(705,'Find K Pairs with Smallest Sums','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-k-pairs-with-smallest-sums/',1),
(705,'Smallest Range Covering Elements from K Lists','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/',2),
(707,'IPO','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/ipo/',1),
(802,'Number of Islands','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Bloomberg']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-islands/',1),
(802,'Rotting Oranges','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/rotting-oranges/',2),
(802,'01 Matrix','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/01-matrix/',3),
(803,'Max Area of Island','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/max-area-of-island/',1),
(803,'Flood Fill','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/flood-fill/',2),
(803,'Surrounded Regions','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/surrounded-regions/',3),
(804,'Number of Provinces','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-provinces/',1),
(804,'Number of Connected Components in an Undirected Graph','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',2),
(804,'Make Network Connected','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-operations-to-make-network-connected/',3),
(806,'Course Schedule','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Uber']::TEXT[],'LEETCODE','https://leetcode.com/problems/course-schedule/',1),
(806,'Redundant Connection','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/redundant-connection/',2),
(806,'Find Eventual Safe States','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-eventual-safe-states/',3),
(807,'Is Graph Bipartite?','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/is-graph-bipartite/',1),
(807,'Possible Bipartition','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/possible-bipartition/',2),
(807,'Divide Nodes Into the Maximum Number of Groups','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/divide-nodes-into-the-maximum-number-of-groups/',3),
(808,'Course Schedule II','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/course-schedule-ii/',1),
(811,'Network Delay Time','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/network-delay-time/',1),
(811,'Cheapest Flights Within K Stops','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/cheapest-flights-within-k-stops/',2),
(811,'Path With Minimum Effort','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/path-with-minimum-effort/',3),
(812,'Swim in Rising Water','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/swim-in-rising-water/',1),
(815,'Min Cost to Connect All Points','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/min-cost-to-connect-all-points/',1),
(815,'Optimize Water Distribution in a Village','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/optimize-water-distribution-in-a-village/',2),
(815,'Connecting Cities With Minimum Cost','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/connecting-cities-with-minimum-cost/',3),
(901,'Climbing Stairs','EASY',ARRAY['Amazon','Google','Microsoft','Adobe']::TEXT[],'LEETCODE','https://leetcode.com/problems/climbing-stairs/',1),
(901,'Fibonacci Number','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/fibonacci-number/',2),
(901,'Min Cost Climbing Stairs','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/min-cost-climbing-stairs/',3),
(902,'House Robber','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/house-robber/',1),
(902,'House Robber II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/house-robber-ii/',2),
(902,'Decode Ways','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/decode-ways/',3),
(903,'Unique Paths','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/unique-paths/',1),
(903,'Minimum Path Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-path-sum/',2),
(903,'Triangle','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/triangle/',3),
(904,'Unique Paths II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/unique-paths-ii/',1),
(904,'Minimum Falling Path Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-falling-path-sum/',2),
(904,'Dungeon Game','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/dungeon-game/',3),
(905,'Longest Common Subsequence','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-common-subsequence/',1),
(905,'Distinct Subsequences','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/distinct-subsequences/',2),
(905,'Uncrossed Lines','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/uncrossed-lines/',3),
(906,'Partition Equal Subset Sum','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/partition-equal-subset-sum/',1),
(906,'Target Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/target-sum/',2),
(906,'Last Stone Weight II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/last-stone-weight-ii/',3),
(907,'Subset Sum Problem','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'GFG','https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/0',1),
(907,'Ones and Zeroes','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/ones-and-zeroes/',2),
(908,'Coin Change','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/coin-change/',1),
(908,'Coin Change II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/coin-change-ii/',2),
(908,'Combination Sum IV','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/combination-sum-iv/',3),
(909,'Perfect Squares','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/perfect-squares/',1),
(910,'Longest Increasing Subsequence','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-increasing-subsequence/',1),
(910,'Number of Longest Increasing Subsequence','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-longest-increasing-subsequence/',2),
(910,'Russian Doll Envelopes','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/russian-doll-envelopes/',3),
(911,'Shortest Common Supersequence','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/shortest-common-supersequence/',1),
(912,'Edit Distance','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/edit-distance/',1),
(912,'Wildcard Matching','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/wildcard-matching/',2),
(912,'Word Break','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/word-break/',3),
(913,'Longest Palindromic Subsequence','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-palindromic-subsequence/',1),
(913,'Palindrome Partitioning II','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/palindrome-partitioning-ii/',2),
(914,'Best Time to Buy and Sell Stock II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/',1),
(914,'Best Time to Buy and Sell Stock III','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/',2),
(914,'Best Time to Buy and Sell Stock with Cooldown','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',3),
(915,'Partition Array for Maximum Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/partition-array-for-maximum-sum/',1),
(915,'Burst Balloons','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/burst-balloons/',2),
(916,'Minimum Cost to Cut a Stick','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-cost-to-cut-a-stick/',1),
(916,'Strange Printer','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/strange-printer/',2),
(1001,'Implement Trie (Prefix Tree)','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/implement-trie-prefix-tree/',1),
(1001,'Design Add and Search Words Data Structure','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/design-add-and-search-words-data-structure/',2),
(1001,'Replace Words','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/replace-words/',3),
(1003,'Longest Word in Dictionary','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-word-in-dictionary/',1),
(1003,'Map Sum Pairs','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/map-sum-pairs/',2),
(1004,'Word Search II','HARD',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/word-search-ii/',1),
(1004,'Magic Dictionary','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/implement-magic-dictionary/',2),
(1101,'Two Sum II - Input Array Is Sorted','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',1),
(1101,'Container With Most Water','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/container-with-most-water/',2),
(1102,'3Sum','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Apple']::TEXT[],'LEETCODE','https://leetcode.com/problems/3sum/',1),
(1103,'Remove Element','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/remove-element/',1),
(1104,'Maximum Average Subarray I','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-average-subarray-i/',1),
(1104,'Permutation in String','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/permutation-in-string/',2),
(1105,'Longest Substring Without Repeating Characters','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Bloomberg']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-substring-without-repeating-characters/',1),
(1105,'Minimum Size Subarray Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-size-subarray-sum/',2),
(1105,'Fruit Into Baskets','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/fruit-into-baskets/',3),
(1106,'Longest Repeating Character Replacement','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/longest-repeating-character-replacement/',1),
(1106,'Max Consecutive Ones III','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/max-consecutive-ones-iii/',2),
(1201,'Pow(x, n)','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/powx-n/',1),
(1204,'Subsets','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/subsets/',1),
(1204,'Subsets II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/subsets-ii/',2),
(1204,'Combination Sum','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/combination-sum/',3),
(1302,'Letter Case Permutation','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/letter-case-permutation/',1),
(1303,'Combinations','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/combinations/',1),
(1303,'Combination Sum III','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/combination-sum-iii/',2),
(1304,'Permutations','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/permutations/',1),
(1304,'Permutations II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/permutations-ii/',2),
(1304,'Permutation Sequence','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/permutation-sequence/',3),
(1306,'N-Queens','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/n-queens/',1),
(1306,'N-Queens II','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/n-queens-ii/',2),
(1306,'Beautiful Arrangement','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/beautiful-arrangement/',3),
(1307,'Sudoku Solver','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/sudoku-solver/',1),
(1307,'Valid Sudoku','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/valid-sudoku/',2),
(1309,'Word Search','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/word-search/',1),
(1309,'Path with Maximum Gold','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/path-with-maximum-gold/',2),
(1401,'Number of 1 Bits','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/number-of-1-bits/',1),
(1401,'Counting Bits','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/counting-bits/',2),
(1401,'Power of Two','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/power-of-two/',3),
(1405,'Single Number','EASY',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/single-number/',1),
(1405,'Single Number II','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/single-number-ii/',2),
(1405,'Single Number III','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/single-number-iii/',3),
(1406,'Maximum Product of Word Lengths','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-product-of-word-lengths/',1),
(1406,'Partition to K Equal Sum Subsets','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/partition-to-k-equal-sum-subsets/',2),
(1501,'Contains Duplicate','EASY',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/contains-duplicate/',1),
(1505,'Contiguous Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/contiguous-array/',1),
(1505,'Continuous Subarray Sum','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/continuous-subarray-sum/',2),
(1602,'Search in a Binary Search Tree','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/search-in-a-binary-search-tree/',1),
(1602,'Two Sum IV - Input is a BST','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/two-sum-iv-input-is-a-bst/',2),
(1602,'Range Sum of BST','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/range-sum-of-bst/',3),
(1603,'Insert into a Binary Search Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/insert-into-a-binary-search-tree/',1),
(1603,'Delete Node in a BST','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/delete-node-in-a-bst/',2),
(1603,'Trim a Binary Search Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/trim-a-binary-search-tree/',3),
(1605,'Kth Smallest Element in a BST','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/kth-smallest-element-in-a-bst/',1),
(1605,'Kth Largest Sum in a Binary Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/kth-largest-sum-in-a-binary-tree/',2),
(1605,'Minimum Absolute Difference in BST','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-absolute-difference-in-bst/',3),
(1606,'Validate Binary Search Tree','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/validate-binary-search-tree/',1),
(1606,'Recover Binary Search Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/recover-binary-search-tree/',2),
(1606,'Maximum Sum BST in Binary Tree','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/',3),
(1702,'Non-overlapping Intervals','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/non-overlapping-intervals/',1),
(1702,'Minimum Number of Arrows to Burst Balloons','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',2),
(1702,'Maximum Length of Pair Chain','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/maximum-length-of-pair-chain/',3),
(1706,'Jump Game','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/jump-game/',1),
(1706,'Jump Game II','MEDIUM',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/jump-game-ii/',2),
(1706,'Jump Game III','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/jump-game-iii/',3),
(1707,'Candy','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/candy/',1),
(1707,'Assign Cookies','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/assign-cookies/',2),
(1707,'Lemonade Change','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/lemonade-change/',3),
(1802,'Merge Intervals','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta','Uber']::TEXT[],'LEETCODE','https://leetcode.com/problems/merge-intervals/',1),
(1803,'Insert Interval','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/insert-interval/',1),
(1803,'Interval List Intersections','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/interval-list-intersections/',2),
(1902,'Greatest Common Divisor of Strings','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/greatest-common-divisor-of-strings/',1),
(1902,'Find Greatest Common Divisor of Array','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-greatest-common-divisor-of-array/',2),
(1902,'Water and Jug Problem','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/water-and-jug-problem/',3),
(1903,'Count Primes','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/count-primes/',1),
(1903,'Ugly Number','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/ugly-number/',2),
(1903,'Prime Number of Set Bits in Binary Representation','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/prime-number-of-set-bits-in-binary-representation/',3),
(1906,'Super Pow','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/super-pow/',1),
(1906,'Power of Three','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/power-of-three/',2),
(2005,'Sort an Array','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/sort-an-array/',1),
(2101,'Find Pivot Index','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/find-pivot-index/',1),
(2101,'Running Sum of 1d Array','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/running-sum-of-1d-array/',2),
(2101,'Left and Right Sum Differences','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/left-and-right-sum-differences/',3),
(2202,'Spiral Matrix','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/spiral-matrix/',1),
(2202,'Diagonal Traverse','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/diagonal-traverse/',2),
(2202,'Set Matrix Zeroes','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/set-matrix-zeroes/',3),
(2203,'Rotate Image','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/rotate-image/',1),
(2203,'Transpose Matrix','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/transpose-matrix/',2),
(2203,'Determine Whether Matrix Can Be Obtained By Rotation','EASY',ARRAY['Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/',3),
(2301,'Accounts Merge','MEDIUM',ARRAY['Amazon','Google','Microsoft','Meta']::TEXT[],'LEETCODE','https://leetcode.com/problems/accounts-merge/',1),
(2303,'Most Stones Removed with Same Row or Column','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/',1),
(2304,'Redundant Connection II','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/redundant-connection-ii/',1),
(2304,'Graph Valid Tree','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/graph-valid-tree/',2),
(2401,'Critical Connections in a Network','HARD',ARRAY['Amazon','Google','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/critical-connections-in-a-network/',1),
(2403,'Reconstruct Itinerary','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/reconstruct-itinerary/',1),
(2403,'Valid Arrangement of Pairs','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/valid-arrangement-of-pairs/',2),
(2403,'Cracking the Safe','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/cracking-the-safe/',3),
(2501,'Range Sum Query - Mutable','MEDIUM',ARRAY['Amazon','Microsoft','Google']::TEXT[],'LEETCODE','https://leetcode.com/problems/range-sum-query-mutable/',1),
(2501,'Falling Squares','HARD',ARRAY['Google','Amazon','Microsoft']::TEXT[],'LEETCODE','https://leetcode.com/problems/falling-squares/',2)
ON CONFLICT (problem_url) DO NOTHING;
-- Optional verification:
SELECT problem_url, COUNT(*) FROM coding_questions GROUP BY problem_url;